---
# tasks file for create_aws_connection
- set_fact:
    present_flag: False
- set_fact:
    present_flag: True
  with_items: "{{ md_connection_dict[monitoring_domain_alias] }}" 
  when: item.alias == connection_alias and (monitoring_domain_alias in md_connection_dict.keys()|list )
  
- ec2_vpc_net_facts:
    filters:
      "tag:Name": "{{ centralized_vpc_name }}"
    


