---
# tasks file for create_aws_connection
- set_fact:
    present_flag: False
- set_fact:
    present_flag: True
  with_items: "{{ md_connection_dict[monitoring_domain_alias] }}" 
  when: item.alias == "{{ connection_alias }}"
    
- name: Create AWS Connection 
  uri:
    url: https://{{ fm_ip }}/api/v1.3/cloud/aws/connections
    method: Post
    user: "{{ fm_username }}"
    password: "{{ fm_password }}"
    force_basic_auth: yes
    validate_certs: False
    return_content: yes
    timeout: 30
    body: {
            "alias": "{{ connection_alias }}",
            "authType": basicCredentials,
            "regionName": "{{ aws_region }}",
            "vpcId": "{{ aws_vpc_id }}",
            "availabilityZone": "{{ aws_availability_zone }}",
            "accessKey": "{{ aws_access_key }}",
            "secretKey": "{{ aws_secret_key }}",
            #"credentialId": "{{ aws_credential_id }}",
            #"proxyServerId": "{{ aws_proxy_server_id }},
            "monitoringDomainId": "{{ md_alias_id_dict[monitoring_domain_alias] }}",
            "secureMirrorTraffic": "{{ aws_secure_mirror_traffic | default(false) }}"
            }
    body_format: json
    status_code: 201,200,409
  register: output
  when:  "{{ present_flag }} == False
- debug:
    msg: "Connection successfully deployed"
  when:  output.status in [200,201]
- debug:
    msg: "Connection with the same alias exists, creation failed"
  when:  output.status in [409]
- debug:
    msg: "Connection deployement failed"
  when:  output.status not in [200,201,409] 
