- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
   - name: Create an ec2 launch template
     community.aws.ec2_launch_template:
       aws_access_key: "{{ aws_access_key }}"
       aws_secret_key: "{{ aws_secret_key }}"
       name: "{{ launch_template_name }}"
       image_id: "{{ vseries_ami_id }}"
       key_name: "{{ aws_key }}"
       instance_type: "{{ vseries_instance_type }}"
       security_groups: "{{ aws_security_group }}"
       instance_type: "{{ vseries_instance_type }}"      
       network_interfaces:
        - associate_public_ip_address: yes
          delete_on_termination: yes
          device_index: 0
          groups: "{{ aws_security_group_eth0 }}"
          subnet_id: "{{ vpc_subnet_id_eth0 }}"
        - associate_public_ip_address: no
          delete_on_termination: yes
          device_index: 1
          groups: "{{ aws_security_group_eth1 }}"
          subnet_id: "{{ vpc_subnet_id_eth1 }}"   
       region: "{{ aws_region }}"
       #iam_instance_profile:

   - name: Create Autoscaling Group 
     amazon.aws.autoscaling_group:
       aws_access_key: "{{ aws_access_key }}"
       aws_secret_key: "{{ aws_secret_key }}"      
       name: "{{ auto_scaling_group_name }}"
       launch_template: 
         launch_template_name: "{{ launch_template_name }}"
       replace_all_instances: true
       vpc_zone_identifier: "{{ vpc_subnet_id_list }}"
       min_size: "{{ autoscale_grp_min_size  }}"
       max_size: "{{ autoscale_grp_max_size}}"
       desired_capacity: "{{ autoscale_grp_desired_capacity }}"
       region: "{{ aws_region }}"
