- hosts: localhost
  connection: local
  gather_facts: false
  
  tasks:
   - name: render template to variable
     set_fact:
       template_value: "{{ lookup('template', 'user_data.j2') }}"

   - name: write base64 encoded user_data.sh
     copy:
       dest: "/tmp/user_data.sh"
       content: "{{ template_value | b64encode }}"
   - name: Gather information about a target group
     community.aws.elb_target_group_info:
       name: "{{ gwlb_target_group_name }}"
     register: output
   - debug:
       msg: "{{ output }}"
