- hosts: localhost
  connection: local
  gather_facts: false 
  tasks:  
    - name: Get Maps
      uri:
        url: https://{{fm_ip}}/api/v1.3/api/v1.3/tokens/create
        method: Post
        user: "{{ fm_username }}"
        password: "{{ fm_password }}"
        force_basic_auth: yes
        validate_certs: False
        return_content: yes
        timeout: 30
        body: {"username": {{ username }},"tokenName": {{ token_name }},"groups": {{ group_list }},"expiryTimeUnit": {{ time_unit|default('DAYS') }},"expiryTime": {{ duration | default(30) }}}
        body_format: json
        status_code: 201,200,204
      register: output

