- hosts: localhost
  connection: local
  gather_facts: false 
  tasks:  
    - name: Create FM user token
      uri:
        url: https://{{fm_ip}}/api/v1.3/tokens/create
        method: POST
        user: "{{ fm_username }}"
        password: "{{ fm_password }}"
        force_basic_auth: yes
        validate_certs: False
        return_content: yes
        timeout: 30
        body: {"username": "{{ username }}","tokenName": "{{ token_name }}","groups": "{{ user_group_list }}","expiryTimeUnit": "{{ time_unit|default('DAYS') }}","expiryTime": "{{ duration | default(30) }}"}
        body_format: json
        status_code: 201,200,204
      register: output
    - debug:
        msg: "Token successfully created"
      when:  output.status in [200,201,204]
    - debug:
        msg: "Token creation not successful"
      when:  output.status not in [200,201,204]

