- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
   - name: create launch config
     community.aws.autoscaling_launch_config:
       aws_access_key: "{{ aws_access_key }}"
       aws_secret_key: "{{ aws_secret_key }}"
       name: "{{ launch_template_name }}"
       image_id: "{{ vseries_ami_id }}"
       key_name: "{{ aws_key }}"
       region: "{{ aws_region }}"
       security_groups: "{{ aws_security_group }}"
       instance_type: "{{ vseries_instance_type }}"

   - name: Create Autoscaling Group 
     amazon.aws.autoscaling_group:
       aws_access_key: "{{ aws_access_key }}"
       aws_secret_key: "{{ aws_secret_key }}"      
       name: "{{ auto_scaling_group_name }}"
       launch_config_name: "{{ launch_template_name }}"
       replace_all_instances: true
       vpc_zone_identifier: "{{ vpc_subnet_id_list }}"
       min_size: "{{ autoscale_grp_min_size  }}"
       max_size: "{{ autoscale_grp_max_size}}"
       desired_capacity: "{{ autoscale_grp_desired_capacity }}"
       region: "{{ aws_region }}"
    
   - name: create TargetTrackingScaling custom policy
     ec2_scaling_policy:
       aws_access_key: "{{ aws_access_key }}"
       aws_secret_key: "{{ aws_secret_key }}"      
       name: "target-tracking-policy"
       policy_type: TargetTrackingScaling
       target_tracking_config:
         predefined_metric_spec:
           predefined_metric_type: ASGAverageNetworkIn
         target_value: 98.0
       asg_name: "{{ auto_scaling_group_name }}"
       estimated_instance_warmup: 300
       region: "{{ aws_region }}"
     register: result
      
   - name: Gather Facts for the auto scaling group
     community.aws.ec2_asg_info:
       aws_access_key: "{{ aws_access_key }}"
       aws_secret_key: "{{ aws_secret_key }}"     
       name:  "{{ auto_scaling_group_name }}"
       region: "{{ aws_region }}"
     register: asgs
   - debug:
       msg: "{{ asgs.results }}"
   - set_fact:
       vseries_instance_list: "{{ item.instances }}'
     with_item: '{{ asgs.results }}"
