- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  
   - name: create TargetTrackingScaling custom policy
     ec2_scaling_policy:
       aws_access_key: "{{ aws_access_key }}"
       aws_secret_key: "{{ aws_secret_key }}"      
       name: "target-tracking-policy"
       state: absent
       region: "{{ aws_region }}" 

   - name: Create Autoscaling Group 
     amazon.aws.autoscaling_group:
       aws_access_key: "{{ aws_access_key }}"
       aws_secret_key: "{{ aws_secret_key }}"      
       name: "{{ auto_scaling_group_name }}"
       launch_config_name: "{{ launch_template_name }}"
       state: absent
       region: "{{ aws_region }}"
       
   - name: create launch config
     community.aws.autoscaling_launch_config:
       aws_access_key: "{{ aws_access_key }}"
       aws_secret_key: "{{ aws_secret_key }}"
       name: "{{ launch_template_name }}"
       region: "{{ aws_region }}"
       state: absent
       assign_public_ip: true


    


