- hosts: localhost
  connection: local
  gather_facts: false 
  tasks:    
    - name: GVOS node inventory from FM
      uri:
        headers:
          Content-Type: application/json
          Authorization: "Bearer {{ bearer_token }}"
        url: https://{{fm_ip}}/api/v1.3/nodes/flat
        method: GET
        force_basic_auth: yes
        validate_certs: False
        return_content: yes
        timeout: 30
        body_format: json
        status_code: 201,200, 204
      register: output

    
