- hosts: localhost
  connection: local
  gather_facts: false 
  
  tasks:  
    - name: Get Stats at 5 minute intervals
      shell: "curl -k -u {{fm_username}}:{{fm_password}} -X 'GET' 'https://{{fm_ip}}/api/v1.3/elasticUtils/queryIndices?since={{interval}}&indexPattern=fmevents&size=10000'  -H 'accept: application/json'"
      register: output
    - debug:
        var: output
        
    - debug:
        var: "{{ output.stdout_lines | replace('"',"" }}"
      
    - debug:
        var: "{{ output.stdout_lines }}"
        

