- hosts: localhost
  connection: local
  gather_facts: false 
  
  tasks:  
    - name: Get Stats at 5 minute intervals
      shell: "curl -k -u {{fm_username}}:{{fm_password}} -X GET https://{{fm_ip}}/api/0.9/elasticUtils/queryIndices?since=5-minute&indexPattern=fmevents&size=10000&scroll=false&trending=false&rate=false&exclude=true&inventoryIndex=false&skipNormalized=false&skipZeroValues=false&isSourceReqInAggregation=true"
      args:
        warn: False
      register: output

    - debug:
        var: "{{ output | to_json }}"
