- hosts: localhost
  connection: local
  gather_facts: false 
  
  tasks:  
    - name: Get Stats at 5 minute intervals
      shell: "curl -k -u {{fm_username}}:{{fm_password}} -X 'GET' 'https://{{fm_ip}}/api/v1.3/elasticUtils/queryIndices?since={{interval}}&indexPattern=fmevents&size=10000'  -H 'accept: application/json,Content-Type: application/json'"
      register: output

    - set_fact:
        output_events: "{{ item }}"
      with_items: "{{ output.stdout_lines }}"
      when: item == "hits"
      
    - debug:
        var: output_events
        
    - debug:
        var: output.stdout_lines
