- hosts: localhost
  connection: local
  collections:
   - community.vmware
  gather_facts: false 
  tasks:  
  - name: Gather only registered virtual machines
    vmware_vm_info:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      validate_certs: no 
      vm_type: vm
    delegate_to: localhost
    register: vm_info

  - debug:
      var: vm_info.virtual_machines
