- hosts: all
  collections:
   - damhau.ansible_for_nsxt
  tasks: 
    - name: Check manager status
      nsxt_manager_status:
          hostname: "{{ nsx_node_ip  }}"
          username: "{{ nsx_username }}"
          password: "{{ nsx_password }}"
          validate_certs: False
          wait_time: 50
