- hosts: gigamon_nodes
  connection: local
  gather_facts: false
  vars_prompt:
    - name: fm_ip
      prompt: "Enter FM IP"
      private: false
    - name: fm_username
      prompt: "Enter FM Username"
      private: false
    - name: fm_password
      prompt: "Enter FM password"
      private: true
    - name: node_username
      prompt: "Enter node username"
      private: false
    - name: node_password
      prompt: "Enter node password"
      private: true	  
  roles: 
    - add_node_to_fm

