---
# tasks file for create_monitoring_domain
- name: Verify if monitoring domain exists
  set_fact:
    flag: "{{ True if monitoring_domain_alias in md_alias_id_dict.keys()|list else False }}"
    
- name: Create Monitoring Domain
  uri:
    url: https://{{fm_ip}}/api/v1.3/cloud/monitoringDomains
    method: Post
    user: "{{ fm_username }}"
    password: "{{ fm_password }}"
    force_basic_auth: yes
    validate_certs: False
    return_content: yes
    timeout: 30
    body: {
            "alias": "{{ monitoring_domain_alias }}",
            "useLoadBalancer": false,
            "mtu": "{{ mtu | default(9100) }}",
            "platform": "{{ platform }}"
            }
    body_format: json
    status_code: 201,200,409
  register: output
  when: "{{ flag }}" == False

  
- debug:
    msg: "Monitoring Domain successfully deployed"
  when:  output.status in [200,201] and "{{ flag }}" == False
  
- debug:
    msg: "Monitoring Domain with the same alias exists and has monitoring domain ID {{ md_alias_id_dict [ monitoring_domain_alias ] }}, creation failed"
  when:  "{{ flag }}" == True
  
- debug:
    msg: "Monitoring Domain deployment failed"
  when:  output.status not in [200,201,409] and "{{ flag }}" == False
