---
# tasks file for create_monitoring_domain
-name: Verify if monitoring domain exists
 block: 
  - name: Set flag True
    set_fact:
      flag: True
    when: "{{ monitoring_domain_alias }}" in "{{ md_alias_id_dict.keys()|list }}"
  - name: Set flag False
    set_fact:
      flag: False
    when: "{{ monitoring_domain_alias }}" not in "{{ md_alias_id_dict.keys()|list }}"  
    
- name: Create Monitoring Domain
  uri:
    url: https://{{fm_ip}}/api/v1.3/cloud/monitoringDomains
    method: Post
    user: "{{ fm_username }}"
    password: "{{ fm_password }}"
    force_basic_auth: yes
    validate_certs: False
    return_content: yes
    timeout: 30
    body: {
            "alias": "{{ monitoring_domain_alias }}",
            "useLoadBalancer": false,
            "mtu": "{{ mtu | default(9100) }}",
            "platform": "{{ platform }}"
            }
    body_format: json
    status_code: 201,200,409
  register: output

  
- debug:
    msg: "Monitoring Domain successfully deployed"
  when:  output.status in [200,201]
  
- debug:
    msg: "Monitoring Domain with the same alias exists and has monitoring domain ID {{ md_alias_id_dict [ monitoring_domain_alias ] }}, creation failed"
  when:  output.status in [409]
  
- debug:
    msg: "Monitoring Domain deployment failed"
  when:  output.status not in [200,201,409]  
