--- 
- name: Create Maps
  uri:
    url: https://{{fm_ip}}/api/v1.3/maps/{{ map_alias }}?clusterId={{ cluster_id }}
    method: Delete
    user: "{{ fm_username }}"
    password: "{{ fm_password }}"
    force_basic_auth: yes
    validate_certs: False
    return_content: yes
    timeout: 30
    body_format: json
    status_code: 201,200,204
  register: output
