---
# tasks file for get_node_inventory_from_FM
- name: GVOS node inventory from FM
  uri:
    url: https://{{fm_ip}}/api/v1.3/nodes/flat
    method: GET
    user: "{{ fm_username }}"
    password: "{{ fm_password }}"
    force_basic_auth: yes
    validate_certs: False
    return_content: yes
    timeout: 30
    body_format: json
    status_code: 201,200, 204
  register: output
- set_fact:
    node_list: "{{ node_list|default([]) + [item.deviceIp] }}"
  with_items: "{{ output.json.nodes }}"
- debug:
    var: node_list
