---
# tasks file for create_azure_connection
- set_fact:
    present_flag: False
    
- set_fact:
    present_flag: True
  with_items: "{{ md_connection_dict[monitoring_domain_alias] }}" 
  when: item.alias == connection_alias and (monitoring_domain_alias in md_connection_dict.keys()|list )
    
- name: Create Azure Connection 
  uri:
    url: https://{{ fm_ip }}/api/v1.3/cloud/azure/connections
    method: Post
    user: "{{ fm_username }}"
    password: "{{ fm_password }}"
    force_basic_auth: yes
    validate_certs: False
    return_content: yes
    timeout: 30
    body: {
            "alias": "{{ connection_alias }}",
            "authType": "{{ azure_auth_type| default(managedServiceIdentity) }}",
            "regionName": "{{ azure_region }}",
            "subscriptionId": "{{ azure_subscription_id }}",
            "tenantId": "{{ azure_tenant_id }}",
            "applicationClientId": "{{ azure_application_client_id }}",
            "applicationSecretKey": "{{ azure_application_secret_key }}",
            "virtualNetworkId": "{{ azure_virtual_network_id }}",
            #"credentialId": "{{ azure_credential_id }}",
            "resourceGroupNames": "{{ azure_resource_group_names_list }}",
            "monitoredResourceGroupNames": "{{ azure_monitored_resource_group_names }}",
            "msiPort": "{{ azure_msi_port| default(0) }}",
            #"proxyServerId": "{{ azure_proxy_server_id }}",
            "monitoringDomainId": "{{ md_alias_id_dict[monitoring_domain_alias] }}",
            "secureMirrorTraffic": "{{ azure_secure_mirror_traffic | default(false) }}"
            }
    body_format: json
    status_code: 201,200,409
  register: output
  when:  not present_flag 
