---
# tasks file for deploy_fm_vmware
- name: Deploy VCSA OVF to vCenter
  community.vmware.vmware_deploy_ovf:
    hostname: '{{ vmware_ip }}'
    username: '{{ vmware_username }}'
    password: '{{ vmware_password }}'
    datacenter: '{{ vmware_datacenter }}'
    name: '{{ vm_name }}' 
    validate_certs: False
    datastore: '{{ vmware_datastore }}'
    networks:
      name: '{{ vmware_network_name }}'
    ova: '{{ fm_ova_image_path }}'
    inject_ovf_env: yes
    wait: yes
    wait_for_ip_address: no
    properties:
      Mgmt_Port_IP: '{{ management_ip }}'
      Mgmt_Port_Netmask: '{{ management_ip_netmask }}'
      password: '{{ fm_admin_password }}'
      datadisksize: "40"
  delegate_to: localhost
- name: Change adapter
  community.vmware.vmware_guest_network:
    hostname: '{{ vmware_ip }}'
    username: '{{ vmware_username }}'
    password: '{{ vmware_password }}'
    datacenter: '{{ vmware_datacenter }}'
    validate_certs: False
    name: '{{ vm_name }}'
    gather_network_info: True
    networks:
      - state: present
        label: "Network adapter 1"
        name: '{{ vmware_network_name }}'
  delegate_to: localhost