---
# tasks file for delete_system_user
- name: delete system user
  uri:
    url: https://{{fm_ip}}/api/v1.3/system/localUsers/{{ username }}?clusterId={{ cluster_id }}
    method: Delete
    user: "{{ fm_username }}"
    password: "{{ fm_password }}"
    force_basic_auth: yes
    validate_certs: False
    return_content: yes
    timeout: 30
    body_format: json
    status_code: 201,200,204
