---
# tasks file for delete_node_from_FM
- name: Delete GVOS node from FM
  uri:
    url: https://{{fm_ip}}/api/v1.3/nodes?async=false
    method: Delete
    user: "{{ fm_username }}"
    password: "{{ fm_password }}"
    force_basic_auth: yes
    validate_certs: False
    return_content: yes
    timeout: 30
    body_format: json
    status_code: 201,200,204
  register: output
