---
# tasks file for get_monitoringDomain_facts
- name: Get Monitoring Domain Facts
  uri:
	url: https://{{ input.fm_ip }}/api/v1.3/cloud/monitoringDomains?platform=vmware
	method: GET
	user: "{{ fm_username }}"
	password: "{{ fm_password }}"
	force_basic_auth: yes
	validate_certs: False
	return_content: yes
	timeout: 30
	body_format: json
	status_code: 201,200
  register: output  
  
- set_fact:
	facts_md_dict: "{{ facts_md_dict|default({}) | combine ({item.id : item.alias}) }}"
  with_items: "{{ output.json.monitoringDomains }}"
  
- set_fact:
	md_alias_id_dict: "{{ md_alias_id_dict|default({}) | combine ({item.id : item.alias}) }}"
  with_items: "{{ output.json.monitoringDomains }}"  
  
- set_stats:
	data:
	  facts_md_dict: "{{ facts_md_dict|default({}) | combine ({item.id : item.alias}) }}"
  with_items: "{{ output.json.monitoringDomains }}"
  
- set_stats:
	data:
	  md_alias_id_dict: "{{ md_alias_id_dict|default({}) | combine ({ item.alias : item.id}) }}"
  with_items: "{{ output.json.monitoringDomains }}" 
  
- debug:
	var: facts_md_dict  
- set_fact:
	facts_vseries_dict: "{{ facts_vseries_dict|default({}) | combine ({ facts_dict[item] : facts_conn_dict[item]}) }}"
  with_items: "{{ facts_dict.keys() }}"
- set_stats:
	data:
	  facts_vseries_dict: "{{ facts_vseries_dict|default({}) | combine ({ facts_dict[item] : facts_conn_dict[item]}) }}"
  with_items: "{{ facts_dict.keys() }}"     
- debug:
	var: facts_vseries_dict
