---
# tasks file for get_monitoringDomain_facts
- name: Get Monitoring Domain Facts
  uri:
    url: https://{{ fm_ip }}/api/v1.3/cloud/monitoringDomains?platform={{ platform }}
    method: GET
    user: "{{ fm_username }}"
    password: "{{ fm_password }}"
    force_basic_auth: yes
    validate_certs: False
    return_content: yes
    timeout: 30
    body_format: json
    status_code: 201,200
  register: output  
  
- set_fact:
    facts_md_dict: "{{ facts_md_dict|default({}) | combine ({item.id : item.alias}) }}"
  with_items: "{{ output.json.monitoringDomains }}"
  
- set_fact:
    md_alias_id_dict: "{{ md_alias_id_dict|default({}) | combine ({item.alias : item.id}) }}"
  with_items: "{{ output.json.monitoringDomains }}"  
  
- set_fact:
    md_connection_dict: "{{ md_connection_dict|default({}) }}"

- set_fact:
    md_connection_dict: "{{ md_connection_dict|default({}) | combine ({item.alias : item.connections}) }}"
  with_items: "{{ output.json.monitoringDomains }}"  
  when: "'connections' in item.keys()|list"

- set_fact:
    md_connection_dict: "{{ md_connection_dict|combine ({item.alias : [] }) }}"
  with_items: "{{ output.json.monitoringDomains }}"  
  when: "'connections' not in item.keys()|list"
  
- set_fact:
    md_dict_info: "{{ md_dict_info|default({}) | combine ({item.alias : item}) }}"
  with_items: "{{ output.json.monitoringDomains }}"  
  
- debug:
    msg: md_dict_info  
    
- debug:
    msg: md_connection_dict
