--- 
- name: Create Maps
  uri:
    url: https://{{fm_ip}}/api/v1.3/maps?clusterId={{ cluster_id }}
    method: Post
    user: "{{ fm_username }}"
    password: "{{ fm_password }}"
    force_basic_auth: yes
    validate_certs: False
    return_content: yes
    timeout: 30
    body: {alias: "{{ map_alias }}", type: "{{ map_type }}" , enable: "{{ map_state | default(true) }}", comment: "{{ map_comment }}", subType: "{{ map_sub_type }}",
           srcPorts: "{{ map_src_port_list }}", dstPorts: "{{ map_dst_port_list }}", rules: "{{ map_rules }}", clusterId: "{{ cluster_id }}"}
    body_format: json
    status_code: 201,200
  register: output
- debug:
    msg: "Connection successfully deployed"
  when:  output.status in [200,201]
- debug:
    msg: "Connection with the same alias exists, creation failed"
  when:  output.status in [409]
