---
# tasks file for create_aws_visibility_domain
- name: Create AWS Visibility Domain
  uri:
    url: https://{{fm_ip}}/api/v1.3/cloud/aws/visibilityDomain
    method: Post
    user: "{{ fm_username }}"
    password: "{{ fm_password }}"
    force_basic_auth: yes
    validate_certs: False
    return_content: yes
    timeout: 30
    body: {
            "name": "{{ monitoring_domain_alias }}",
            tappingMethod": "{{ tapping_method }}",
            "mtu": "{{ visibility_domain_mtu | default(8951) }}",
            "userLaunched": "{{ user_launched_state }}",
            "useLoadBalancer": "{{ load_balancer_state }}",
            "connections": [
            {
            "authType": "{{ authentication_type | default("basicCredentials") }}",     #basicCredentials or ec2InstanceRole
            "regionName": "{{ aws_region }}",
            "vpcs": [
            {
            #"id": "string",
            "name": "{{ aws_vpc_vseries_name }}",
            #"ownerId": "string",
            #"additionalProp1": {}
            },
            {
            #"id": "string",
            "name": "{{ aws_vpc_target_name }}",
            #"ownerId": "string",
            #"additionalProp1": {}
            }
            ],
            "accessKey": "{{ aws_access_key }}",
            "secretKey": "{{ aws_secret_key }}",
            #"credentialId": "string",
            #"proxyServerId": "string",
            #"monitoringDomainId": "string",
            "secureMirrorTraffic": false   
            }
            ],
            "gvTapFilteringEnabled": false
            }
    body_format: json
    status_code: 201,200,409
  register: output
  ignore_errors: True

- debug:
    msg: "Visibility Domain successfully deployed"
  when:  output.status in [200,201] 
  
- debug:
    msg: "Visibility Domain with the same alias exists and has monitoring domain ID {{ md_alias_id_dict [ monitoring_domain_alias ] }}, creation failed"
  when:  output.status in [409]
  
- debug:
    msg: "Visibility Domain deployment failed"
  when:  output.status not in [200,201,409]
