---
# tasks file for create_aws_fabric_deployment_configs
- name: Create AWS Visibility Domain
  uri:
    url: https://{{fm_ip}}/api/v1.3/cloud/aws/loadBalancing/configs?monitoringDomainId="{{ monitoring_domain_id }}" 
    method: Post
    user: "{{ fm_username }}"
    password: "{{ fm_password }}"
    force_basic_auth: yes
    validate_certs: False
    return_content: yes
    timeout: 30
    body: {
          "connId": "{{ aws_vpc_vseries_connection_id }}",
          "loadBalancerName": "{{ aws_gwlb_name }}",
          "loadBalancerArn": "{{ aws_gwlb_arn }}",
          "autoScalingGroupName": "{{ aws_asg_name }}",
          "autoScalingGroupArn": "{{ aws_asg_arn }}"
          }
    body_format: json
    status_code: 201,200,409
  register: output
  ignore_errors: True

- debug:
    msg: "Loadbalancer configuration successfully deployed"
  when:  output.status in [200,201] 
  
  
- debug:
    msg: "Loadbalancer configuration failed"
  when:  output.status not in [200,201]
