---
# tasks file for redefine_snmp_community_config/
- name: Redefine SNMP community configs
  uri:
    url: https://{{fm_ip}}/api/v1.3/system/snmp/community?clusterId={{ cluster_id }}
    method: Put
    user: "{{ fm_username }}"
    password: "{{ fm_password }}"
    force_basic_auth: yes
    validate_certs: False
    return_content: yes
    timeout: 30
    body: {enableCommunityAuth: "{{ snmp_community_auth | default(true) }}",
	   enableMultiCommunity: "{{ snmp_multi_community| default(false) }}",
           communityStrings: snmp_community_strings}
    body_format: json
    status_code: 201,200
  register: output
