---
# tasks file for create_vmware_connection
- name: Create VMware Connection 
  uri:
    url: https://{{ fm_ip }}/api/v1.3/cloud/vmware/connections
    method: Post
    user: "{{ fm_username }}"
    password: "{{ fm_password }}"
    force_basic_auth: yes
    validate_certs: False
    return_content: yes
    timeout: 30
    body: {
            "alias": "{{ connection_alias }}",
            "vcenterIp": "{{ vcenter_ip }}",
            "username": "{{ vcenter_username }}",
            "password": "{{ vcenter_password }}",
            "tappingMethod": "platform",
            "monitoringDomainId": "{{ md_alias_id_dict[monitoring_domain_alias] }}"
            }
    body_format: json
    status_code: 201,200,409
  register: output
  ignore_errors: True
- debug:
    msg: "Connection successfully deployed"
  when:  output.status in [200,201]
- debug:
    msg: "Connection with the same alias exists, creation failed"
  when:  output.status in [409]
- debug:
    msg: "Connection deployment failed"
  when:  output.status not in [200,201,409] 
